version: "3"
services:
  db:
    image: mariadb
    container_name: lemp_mariadb_demo
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
      - ./docker/mysql/data/:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=Q2020@Admin
      - MYSQL_DATABASE=db_chainathos
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin@Q2020
    ports:
      - "3306:3306"
    networks:
      - backend

  php:
    build: ./docker/php
    container_name: lemp_php-fpm_demo
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/php-fpm:/var/log/php-fpm
      #- /etc/localtime:/etc/localtime:ro
    expose:
      - "9000"
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx_demo
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - php
    ports:
      - 80:80
    networks:
      - backend
      - frontend

  #memcached:
  ##    image: memcached:latest
  ##    container_name: lemp_memcached
  ##    ports:
  ##      - "11211:11211"
  ##    volumes:
  ##      - /etc/localtime:/etc/localtime:ro
  ##    restart: always

  redis:
    image: redis
    container_name: lemp_redis_demo
    ports:
      - "8079:6379"
    volumes:
      - ./docker/data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - backend

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin_demo
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

  node:
    build: ./docker/node
    container_name: lemp_node_demo
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - db
      - redis
    environment:
      - NODE_ENV=production
    networks:
      - backend

  kioskregis:
    build: ./chainatkioskregis
    container_name: lemp_kioskregis
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

  kioskmed:
    build: ./chainatkioskmed
    container_name: lemp_kioskmed
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
